name: ebuy_ecommerceapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: San Francisco Display
      fonts:
        - asset: assets/font/SFNSDisplay-Regular.otf
        - asset: assets/font/SFNSDisplay-Medium.otf
          weight: 500
